// <auto-generated />
using System;
using EngenhariaObrasApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EngenhariaObrasApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250714161011_AddUsuarios")]
    partial class AddUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EngenhariaObrasApi.Models.BDI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdministracaoCentral")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("AdministracaoLocal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DespesaFinanceira")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DespesasIndiretas")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Impostos")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MargemLucro")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<decimal>("PosObras")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ReservaTecnica")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Risco")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Seguro")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId")
                        .IsUnique();

                    b.ToTable("BDIs");
                });

            modelBuilder.Entity("EngenhariaObrasApi.Models.CustoAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("CustosAdicionais");
                });

            modelBuilder.Entity("EngenhariaObrasApi.Models.MaoDeObra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HorasTrabalhadas")
                        .HasColumnType("int");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<string>("Profissional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("MaoDeObras");
                });

            modelBuilder.Entity("EngenhariaObrasApi.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("EngenhariaObrasApi.Models.Obra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CustoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("EngenhariaObrasApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EngenhariaObrasApi.Models.BDI", b =>
                {
                    b.HasOne("EngenhariaObrasApi.Models.Obra", "Obra")
                        .WithOne("BDI")
                        .HasForeignKey("EngenhariaObrasApi.Models.BDI", "ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("EngenhariaObrasApi.Models.CustoAdicional", b =>
                {
                    b.HasOne("EngenhariaObrasApi.Models.Obra", "Obra")
                        .WithMany("CustosAdicionais")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("EngenhariaObrasApi.Models.MaoDeObra", b =>
                {
                    b.HasOne("EngenhariaObrasApi.Models.Obra", "Obra")
                        .WithMany("MaoDeObras")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("EngenhariaObrasApi.Models.Material", b =>
                {
                    b.HasOne("EngenhariaObrasApi.Models.Obra", "Obra")
                        .WithMany("Materiais")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("EngenhariaObrasApi.Models.Obra", b =>
                {
                    b.Navigation("BDI")
                        .IsRequired();

                    b.Navigation("CustosAdicionais");

                    b.Navigation("MaoDeObras");

                    b.Navigation("Materiais");
                });
#pragma warning restore 612, 618
        }
    }
}
